### ISSUE TITLE
How to use a code snippet from you and include a copyright notice

### ISSUE THREAD

**Issue by mcrot** [bitlabstudio/django-libs#17]
I'm working on a scientific project (https://topobank.contact.engineering) which is MIT licensed. There I'll need to highlight navigation bar items. In your project, the template tag `navactive`
does exactly what I need, but I don't want to add a dependency to your full project at the moment (maybe later).

Instead I'd like to just use your code for `navactive` and I would like to give a proper attribution to you.  How can this be done in an easy way? Would a comment in my code with a link to your project be sufficient for you or is there a common way to do this?

**Comment by mcrot** [comment]
Another idea would be to simply paste you code and directly above your copyright notice.
That should do it, so I'll close this. Please reopen, if you disagree.

**Comment by mbrochh** [comment]
@mcrot a comment in your code liking to where you find it in our code is good enough IMO. Good luck with your project!
