### ISSUE TITLE
Python 3 incompatible | Classifiers to be added in setup.py

### ISSUE THREAD

**Issue by sick-art** [bitlabstudio/django-libs#18]
I see the commit --> https://github.com/bitlabstudio/django-libs/commit/cdb29c8d146182eea9e3a9dadf8733e70d1278f3 , which says Fixes for 3.5.

`caniusepython3 -p django-libs`
on running above, we get
<img width="534" alt="Screen Shot 2019-07-01 at 3 57 12 PM" src="https://user-images.githubusercontent.com/15994204/60429620-16137480-9c19-11e9-8eef-0e62c3243864.png">

Reason being we need to add `classifiers` in `setup.py`

**Comment by Tyrdall** [comment]
@sick-art Thanks!
Unfortunately this project is not actively maintained at the moment.
Feel free to submit a pull request though!
