### ISSUE TITLE
add License info to setup.cfg

### ISSUE THREAD

**Issue by schumannd** [bitlabstudio/django-libs#20]
currently this package shows up in automated license checkers as UNKNOWN. I think this can be fixed by adding a license key to the [metadata] section in setup.cfg.

**Comment by mbrochh** [comment]
@schumannd yea I guess nothing wrong with that. Would you like to submit a pull request?

**Comment by schumannd** [comment]
That was fast. I saw that the correct key is already in setup.py so it might be a problem on the license parser side.

**Comment by mbrochh** [comment]
Yay! Even better :)
